### ISSUE TITLE
Swagger documentation

### ISSUE THREAD

**Issue by AchalaSB** [KIPFoundation/varna#13]
**Acceptance Criteria:**
1. Swagger Docs with the routes definition for the build command of all file types - C, C++, and Rust.
2. All request fields specified by type & name. 
3. Plus the response fields specified by the type along with HTTP Codes.

**Comment by AchalaSB** [comment]
Child of #1

**Comment by 0zAND1z** [comment]
@ayushgupta0610 to test & confirm the AC
